version: '3'
services:
  transparent-1:
    image: moltch/fake-service:latest
    environment:
      - SERVICE=transparent-1
    depends_on:
      - transparent-1-dpp
    network_mode: "service:transparent-1-dpp"
  transparent-1-dpp:
    build:
      context: .
      dockerfile: ../dpp.Dockerfile
    cap_add:
      - NET_ADMIN
      - CAP_SYS_ADMIN
    entrypoint: "/bin/sh"
    user: "root"
    environment:
      - "CP_HOSTNAME=kuma-control-plane"
      - "SERVICE_NAME=transparent-1"
      - "SERVICE_PORT=9090"
      - "PORT=9000"
    command:
      - /setup-transparent.sh
    volumes:
      - ../setup-transparent.sh:/setup-transparent.sh
    networks:
      kuma-play: {}
  transparent-2:
    image: moltch/fake-service:latest
    environment:
      - SERVICE=transparent-2
      - UPSTREAM_URIS=http://transparent-1.mesh
    depends_on:
      - transparent-2-dpp
    network_mode: "service:transparent-2-dpp"
  transparent-2-dpp:
    build:
      context: .
      dockerfile: ../dpp.Dockerfile
    cap_add:
      - NET_ADMIN
      - CAP_SYS_ADMIN
    entrypoint: "/bin/sh"
    user: "root"
    environment:
      - "CP_HOSTNAME=kuma-control-plane"
      - "SERVICE_NAME=transparent-2"
      - "SERVICE_PORT=9090"
      - "PORT=9000"
    command:
      - /setup-transparent.sh
    volumes:
      - ../setup-transparent.sh:/setup-transparent.sh
    networks:
      kuma-play: {}
  gateway:
    image: kong/kong-gateway:2.5.0.0-alpine
    user: kong:kong
    environment:
      - "KONG_DATABASE=postgres"
      - "KONG_PG_HOST=postgres"
      - "KONG_PG_PASSWORD=kong"
      - "KONG_PROXY_ACCESS_LOG=/dev/stdout"
      - "KONG_ADMIN_ACCESS_LOG=/dev/stdout"
      - "KONG_PROXY_ERROR_LOG=/dev/stderr"
      - "KONG_ADMIN_ERROR_LOG=/dev/stderr"
      - "KONG_ADMIN_LISTEN=0.0.0.0:8001"
    command:
      - "/bin/bash"
      - "-c"
      - "sleep 5; kong migrations bootstrap; kong start --run-migrations"
    depends_on:
      - postgres
    network_mode: "service:gateway-dpp"
  gateway-dpp:
    build:
      context: .
      dockerfile: ../dpp.Dockerfile
    cap_add:
      - NET_ADMIN
      - CAP_SYS_ADMIN
    entrypoint: "/bin/sh"
    user: "root"
    environment:
      - "CP_HOSTNAME=kuma-control-plane"
      - "DP_FILE=/dp.yaml"
      - "SERVICE_NAME=gateway"
    command:
      - /setup-transparent.sh
    volumes:
      - ../setup-transparent.sh:/setup-transparent.sh
      - ./gateway-dp.yaml:/dp.yaml
    ports:
      - '8000:8000'
      - '8443:8443'
      - '8001:8001'
      - '8444:8444'
      - '8002:8002'
      - '8445:8445'
      - '8003:8003'
      - '8004:8004'
    networks:
      kuma-play: {}
  postgres:
    image: postgres:10.5
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_PASSWORD=kong
      - POSTGRES_DB=kong
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    networks:
      kuma-play: {}

networks:
  kuma-play:
    external:
      name: core_kuma-play
