---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ns-dns-vl3

bases:
- https://github.com/networkservicemesh/deployments-k8s/apps/nse-vl3-vpp?ref=23c5e9bd151a2ec204932e8b06190efa07b5df88
- https://github.com/networkservicemesh/deployments-k8s/apps/vl3-ipam?ref=23c5e9bd151a2ec204932e8b06190efa07b5df88

resources:
- namespace.yaml

patchesStrategicMerge:
- nse-patch.yaml
