---

- name: Create installation directory
  ansible.builtin.file:
    path: "{{ kuma_bindir }}"
    state: directory
    mode: "0755"

- name: Copy kumactl
  ansible.posix.synchronize:
    src: "{{ builddir }}/artifacts-linux-amd64/kumactl/kumactl"
    dest: "{{ kuma_bindir }}/kumactl"
    archive: no
    use_ssh_args: yes
  notify:
  - restart kuma services

- name: Copy kuma-cp
  ansible.posix.synchronize:
    src: "{{ builddir }}/artifacts-linux-amd64/kuma-cp/kuma-cp"
    dest: "{{ kuma_bindir }}/kuma-cp"
    archive: no
    use_ssh_args: yes
  notify:
  - restart kuma services

- name: Copy kuma-dp
  ansible.posix.synchronize:
    src: "{{ builddir }}/artifacts-linux-amd64/kuma-dp/kuma-dp"
    dest: "{{ kuma_bindir }}/kuma-dp"
    archive: no
    use_ssh_args: yes
  notify:
  - restart kuma services

- name: Copy coredns
  ansible.posix.synchronize:
    src: "{{ builddir }}/artifacts-linux-amd64/coredns/coredns"
    dest: "{{ kuma_bindir }}/coredns"
    archive: no
    use_ssh_args: yes
  notify:
  - restart kuma services

- name: Copy test-server
  ansible.posix.synchronize:
    src: "{{ builddir }}/artifacts-linux-amd64/test-server/test-server"
    dest: "{{ kuma_bindir }}/test-server"
    archive: no
    use_ssh_args: yes
  notify:
  - restart kuma services

- name: Copy kuma-prometheus-sd
  ansible.posix.synchronize:
    src: "{{ builddir }}/artifacts-linux-amd64/kuma-prometheus-sd/kuma-prometheus-sd"
    dest: "{{ kuma_bindir }}/kuma-prometheus-sd"
    archive: no
    use_ssh_args: yes
  notify:
  - restart kuma services

