---

- name: Add kuma role group
  ansible.builtin.group:
    name: kuma

- name: Add kuma role user
  ansible.builtin.user:
    name: kuma
    comment: kuma role user
    create_home: yes # Some tools (e.g. podman) require a home directory.
    group: kuma
    password: "*"

- name: Install Kuma binaries
  import_tasks: kuma-binaries.yaml

- name: Configure kumactl
  import_tasks: kuma-binaries.yaml

- name: Install Envoy binaries
  import_tasks: envoy.yaml
