---

- name: Add kuma role group
  ansible.builtin.group:
    name: kuma

- name: Add kuma role user
  ansible.builtin.user:
    name: kuma
    comment: kuma role user
    create_home: no
    group: kuma
    password: "*"

- name: Create installation directory
  ansible.builtin.file:
    path: "{{ kuma_bindir }}"
    state: directory
    mode: "0755"

- name: Copy kumactl
  ansible.builtin.copy:
    src: "{{ builddir }}/artifacts-linux-amd64/kumactl/kumactl"
    dest: "{{ kuma_bindir }}/kumactl"
    mode: "0755"
  notify:
  - restart kuma services

- name: Copy kuma-cp
  ansible.builtin.copy:
    src: "{{ builddir }}/artifacts-linux-amd64/kuma-cp/kuma-cp"
    dest: "{{ kuma_bindir }}/kuma-cp"
    mode: "0755"
  notify:
  - restart kuma services

- name: Copy kuma-dp
  ansible.builtin.copy:
    src: "{{ builddir }}/artifacts-linux-amd64/kuma-dp/kuma-dp"
    dest: "{{ kuma_bindir }}/kuma-dp"
    mode: "0755"
  notify:
  - restart kuma services

- name: Copy coredns
  ansible.builtin.copy:
    src: "{{ builddir }}/artifacts-linux-amd64/coredns/coredns"
    dest: "{{ kuma_bindir }}/coredns"
    mode: "0755"
  notify:
  - restart kuma services

- name: Copy test-server
  ansible.builtin.copy:
    src: "{{ builddir }}/artifacts-linux-amd64/test-server/test-server"
    dest: "{{ kuma_bindir }}/test-server"
    mode: "0755"
  notify:
  - restart kuma services

- name: Copy kuma-prometheus-sd
  ansible.builtin.copy:
    src: "{{ builddir }}/artifacts-linux-amd64/kuma-prometheus-sd/kuma-prometheus-sd"
    dest: "{{ kuma_bindir }}/kuma-prometheus-sd"
    mode: "0755"
  notify:
  - restart kuma services
