---

- name: restart {{ service_name}} dataplane
  listen: restart kuma services
  ansible.builtin.systemd:
    name: "{{ service_name }}-dataplane"
    state: restarted

- name: reload {{ service_name}} dataplane
  ansible.builtin.systemd:
    name: "{{ service_name }}-dataplane"
    state: restarted
    enabled: true
    daemon_reload: yes

