---
apiVersion: v1
kind: Namespace
metadata:
  name: kuma-demo
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: kuma-demo
  name: dataplane-file
data:
  app-dataplane.yaml: |
    type: Dataplane
    mesh: default
    name: demo-app
    networking:
      address: front-page.my-vl3-network
      outbound:
        - port: 16379
          tags:
            kuma.io/service: redis
      inbound:
        - port: 15000
          servicePort: 5000
          tags:
            kuma.io/service: app
            kuma.io/protocol: http
      admin:
        port: 9902
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: kuma-demo
spec:
  selector:
    matchLabels:
      app: demo-app
  replicas: 1
  template:
    metadata:
      annotations:
        networkservicemesh.io: kernel://my-vl3-network@my.cluster1/nsm-1?dnsName=front-page
      labels:
        app: demo-app
    spec:
      volumes:
        - name: config
          configMap:
            name: dataplane-file
            items:
              - key: app-dataplane.yaml
                path: app-dataplane.yaml
      containers:
        - name: demo-app
          image: "kumahq/kuma-demo"
          env:
            - name: REDIS_PORT
              value: "16379"
          ports:
            - name: http
              containerPort: 5000
        - args:
          - run
          - --cp-address=https://control-plane-kuma.my-vl3-network:5678/
          - --dataplane-file=/etc/app-dataplane.yaml
          - --log-level=info
          image: docker.io/kumahq/kuma-dp:1.7.0-amd64
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /etc/app-dataplane.yaml
              name: config
              subPath: app-dataplane.yaml
          name: kuma-sidecar
          resources:
            limits:
              cpu: "1"
              memory: 512Mi
            requests:
              cpu: 50m
              memory: 64Mi
          securityContext:
            runAsGroup: 5678
            runAsUser: 5678
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app
  namespace: kuma-demo
spec:
  selector:
    app: demo-app
  ports:
  - protocol: TCP
    appProtocol: http
    port: 5000
