---

- hosts: all
  roles:
  - role: all
    become: yes
  - role: install-kuma
    become: yes

- hosts: controlplane
  roles:
  - role: install-kuma
    become: yes
  - role: control-plane
    become: yes

- hosts: echoserver
  roles:
  - role: install-kuma
    become: yes
  - role: echo-server
    become: yes
    listen_port: 8080
