---

- hosts: all
  roles:
  - role: all
    become: yes

- hosts: controlplane
  roles:
  - role: install-kuma
    become: yes
  - role: control-plane
    become: yes

- hosts: echoserver
  roles:
  - role: install-kuma
    become: yes
  - role: echo-server
    become: yes
    listen_port: 8080
  - role: data-plane
    become: yes
    service_name: echo
    service_port: 20000
    workload_port: 8080
